version: 1

before:
  hooks:
    - go mod tidy
    - go generate ./...
    - sh -c 'cd $GITHUB_WORKSPACE && if [ -d "dashboards" ]; then tar -czf dashboards-{{ .Version }}.tar.gz dashboards/; else echo "dashboards directory not found, skipping"; fi'
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - freebsd
      - openbsd
      - netbsd
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X 'main.Version={{.Version}}'
      - -X 'main.VersionHash={{.ShortCommit}}'
      - -X 'main.VersionDate={{.Date}}'

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}-
      v{{- .Version }}.
      {{- .Os }}-
      {{- .Arch }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - CHANGELOG.md
      - README.md

release:
  extra_files:
    - glob: dashboards-*.tar.gz

checksum:
  name_template: 'sha256sums.txt'
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
